sudo: required
language: bash
dist: xenial
services:
  - docker

script:
  # build the Docker image using the Docker tool, osc cannot be easily used in Travis
  - cd package
  - docker build -t yast-test-image -f Dockerfile .
  # just some smoke tests, make sure rake and YaST work properly,
  # ensure there is no leftover in the working directory
  - docker run -it --privileged --rm yast-test-image rake -r yast/rake -V
  - docker run -it --privileged --rm -e TERM=xterm yast-test-image yast2 proxy summary
  # check the Travis script
  - docker run -it --privileged --rm yast-test-image shellcheck /usr/local/bin/yast-travis-ruby

